import React, { Component } from 'react'
import PropTypes from 'prop-types'
import { connect } from 'react-redux'
import { Helmet } from 'react-helmet'
import { Link } from 'react-router-dom'

import { Grid, GridCell } from '../../ui/grid'
import ImageTile from '../../ui/image/Tile'
import { H3, H4, H6 } from '../../ui/typography'
import { grey, grey2 } from '../../ui/common/colors'
